# Generated by Django 3.0.3 on 2020-03-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSafeNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafe_news',
            name='news_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
