# Generated by Django 3.0.3 on 2020-03-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSafeNews', '0002_foodsafe_news_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafe_news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
