# Generated by Django 3.0.3 on 2020-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodSafe_blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=30)),
                ('legal_rep', models.CharField(blank=True, max_length=30, null=True)),
                ('punishment', models.CharField(blank=True, max_length=30, null=True)),
                ('criminal_behavior', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
