# Generated by Django 3.0.3 on 2020-03-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSafeCases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafe_cases',
            name='domicile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
